// Copyright © 2018-2023 ARVI VR Inc.
#pragma once

typedef size_t REQUEST_ID;
typedef void* RESPONSE_ID;
typedef void* MESSAGE_ID;
typedef void* EVENT_ID;
typedef void* EVENT_LIST_PTR;

#define INVALID_ID ((size_t)0)

typedef enum {
	REQUEST_UNKNOWN = 0,
	REQUEST_SIMPLE = 1,
	REQUEST_DATA = 2,
	REQUEST_SESSION_DATA_INIT = 3
} REQUEST_TYPE;

typedef enum
{
	TEAM_PUBLIC = 0,
	TEAM_1 = 1,
	TEAM_2 = 2,
	TEAM_3 = 3,
	TEAM_4 = 4,
	TEAM_5 = 5,
	TEAM_6 = 6,
	TEAM_7 = 7,
	TEAM_8 = 8,
	TEAM_9 = 9,
	TEAM_10 = 10,
} TEAM_ID;

typedef enum
{
	DOMINANT_HAND_NOT_SET = 0,
	DOMINANT_HAND_LEFT = 1,
	DOMINANT_HAND_RIGHT = 2,
	DOMINANT_HAND_ANY = 3
} DOMINANT_HAND;

typedef enum {
	EVENT_NOTIFICATION_UNKNOWN = 0,
	EVENT_NOTIFICATION_PLAYER_NAME_CHANGED = 1,
	EVENT_NOTIFICATION_PLAYER_DOMINANT_HAND_CHANGED = 2
} EVENT_NOTIFICATION_TYPE;

typedef enum {
	SESSION_VARIABLE_NO_ERROR = 0,
	SESSION_VARIABLE_NO_CNAHGE = 1,
	SESSION_VARIABLE_NAME_LIMIT = 2,
	SESSION_VARIABLE_VALUE_LIMIT = 3,
	SESSION_VARIABLE_DATA_LIMIT = 4,
	SESSION_VARIABLE_NOT_INIT = 5,
} SESSION_VARIABLE_SET_DATA_RESULT;

typedef enum {
	ERROR_NONE = 0,
	ERROR_UNKNOWN = -1,
	ERROR_BAD_RESPONSE_ID = -2,
	ERROR_REQUEST_LIMIT = -3,

	ERROR_SESSION_VARIABLE_NAME_LIMIT = -4,
	ERROR_SESSION_VARIABLE_VALUE_LIMIT = -5,
	ERROR_SESSION_VARIABLES_SIZE_LIMIT = -6,
	ERROR_SESSION_VARIABLES_NOT_INITIALIZED = -7,
	ERROR_SET_SESSION_VARIABLE_FAILED = -8,
	ERROR_INIT_SESSION_VARIABLES_FAILED = -9,
	ERROR_PARSE_SESSION_VARIABLES_FAILED = -9,

	ERROR_LOAD_APP_KEY = 1,
	ERROR_CREATE_AUTH_DATA = 2,
	ERROR_AUTHENTICATION = 3,

	ERROR_REQUEST_SEND = 4,
	
	ERROR_HTTP = 5
} ERROR_CODE;
